Fix architecture detection on Windows ARM64
When running an AMD64 Python on a Windows ARM64 host, platform.machine()
returns the host architecture instead of the process architecture, causing
sounddevice to try and load the wrong DLL.

    >>> import sounddevice
    Traceback (most recent call last):
      File "C:\Users\bagpuss\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sounddevice.py", line 72, in <module>
        raise OSError('PortAudio library not found')
    OSError: PortAudio library not found

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<python-input-1>", line 1, in <module>
        import sounddevice
      File "C:\Users\bagpuss\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sounddevice.py", line 91, in <module>
        _lib: ... = _ffi.dlopen(_libname)
                    ~~~~~~~~~~~^^^^^^^^^^
    OSError: cannot load library 'C:\Users\bagpuss\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\_sounddevice_data\portaudio-binaries\libportaudioarm64.dll': error 0x7e

Switch to sysconfig.get_platform() which does the right thing under
emulation.